a.out:	main.o	fcfs.o	roundRobin.o	spn.o	srt.o	hrrn.o	feedback.o	helper.o
	gcc -o a.out main.o fcfs.o roundRobin.o spn.o srt.o hrrn.o feedback.o helper.o
main.o: main.c
	gcc -c main.c
fcfs.o: fcfs.c
	gcc -c fcfs.c
roundRobin.o: roundRobin.c
	gcc -c roundRobin.c
spn.o: spn.c
	gcc -c spn.c
srt.o: srt.c
	gcc -c srt.c
hrrn.o: hrrn.c
	gcc -c hrrn.c
feedback.o: feedback.c
	gcc -c feedback.c
helper.o: helper.c
	gcc -c helper.c
