app.out: main.o Ysera.o Nozdormu.o Malygos.o
	gcc -o app.out main.o Ysera.o Nozdormu.o Malygos.o

main.o: main.c
	gcc -c main.c

Ysera.o: Ysera.c
	gcc -c Ysera.c

Nozdormu.o: Nozdormu.c
	gcc -c Nozdormu.c

Malygos.o: Malygos.c
	gcc -c Malygos.c
